### ISSUE TITLE
Highcharts:Date in the X-Axis extreme right is blinking in Random 25 index chart

### ISSUE THREAD

**Issue by arnabk** [binary-com/webtrader#11]
<a href="https://github.com/parashusg"><img src="https://avatars.githubusercontent.com/u/12329842?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [parashusg](https://github.com/parashusg)**
_Wednesday May 13, 2015 at 19:18 GMT_
_Originally opened as https://github.com/regentmarkets/highcharts/issues/16_

----

Highcharts:Date in the X-Axis extreme right is blinking in Random 25 index chart

Steps to Repro:
1. Access the beta version of highcharts application - http://highcharts.binary.com/beta
2. Focus on the First chart - "Random 25 Index (1d)"
3. Observe the Date in the X-Axis extreme right 

Expected: Date is blinking in the x-axis, Refer to attached video
Actual: It should be displayed properly without any distort or blink

http://screencast.com/t/ZHCIHU3Z5kj

**Comment by inexuscore** [comment]
@parashusg I've carefully tested this on FF, Chrome, IE and Edge and I can confirm that the Date in the X-Axis is not blinking. Perhaps this was an issue before and after moving to the new project it was resolved or maybe it was an artifact in the old version.

If you want, I can capture a video and submit the link here.

**Comment by parashusg** [comment]
Hello @inexuscore, 
I have verified this behavior on latest version of FF, CHROME and SAFARI  on production and found to be working fine. It can be closed.
