### ISSUE TITLE
Indicators: Add one Indicator and then try to remove it without selecting the available indicator from the Remove indicators window

### ISSUE THREAD

**Issue by arnabk** [binary-com/webtrader#12]
<a href="https://github.com/parashusg"><img src="https://avatars.githubusercontent.com/u/12329842?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [parashusg](https://github.com/parashusg)**
_Tuesday May 26, 2015 at 18:14 GMT_
_Originally opened as https://github.com/regentmarkets/highcharts/issues/17_

----

Add one Indicator and then try to remove it without selecting the available indicator from the Remove indicators window

- Expected: It should prompt an alert msg to selct the indicator from the list
- Actual: It's closing the window without any action 

RemoveIndicators.png
![removeindicators](https://cloud.githubusercontent.com/assets/12329842/7819702/1f026bfa-0401-11e5-8dbb-2952f2c6405d.png)

**Comment by inexuscore** [comment]
Resolved.
https://github.com/binary-com/webtrader/pull/92
