### ISSUE TITLE
Windows Instruction

### ISSUE THREAD

**Issue by chaaya61** [binary-com/webtrader#319]
Unable to get it to work on Windows. Worked up to "cd webtrader". When I try install -g grunt-cli, I get the erro sh.ex: install: command not found. Then I tried "npm install -g grunt-cli" and that appears to have worked though I don't know if that's the right way or not as I don;t know what to expect. Same with "npm install - g bower".
"npm install " works, but "bower install" wouldn't work no matter what I try. 

Then when I go grunt connect, I get the error: sh.exe: grunt: command not found. 

Can someone please provide the right instruction for Windows users who are transitioning from Windows to Linux slowly?

**Comment by ankitbinary** [comment]
Hi, 
could you go to System Setting -> Advance System Settings - > Advance tab -> click on Environment Variables

over there in the system variables list find 'Path' settings.

Try to find this string "C:\Program Files\nodejs\"

this should be present if you installed nodeJS in the default directory.

if present then can you try opening the terminal (git bash) and type node -v 

it should return the version of the node.

if it does return the proper version of node, then 

try installing git bash again with the default settings.

**Comment by arnabk** [comment]
@chaaya61 You have not mentioned if you followed the git and nodejs installation steps properly, mentioned at the beginning. If those did not go well for you, there is no meaning of following the remaining steps. Installation of git and nodejs properly is mandatory to proceed further

**Comment by chaaya61** [comment]
Thanks Ankitbinary and Arnabk.

nodejs and git installed properly. 
node -v returns v4.4.2.
I was able to use git bash and download webtrader successfully. 

I am stuck on "install -g bower" which wouldn't work and in turn "bower install" of course wouldn't work. 

I guess the main issue is where are all these files installed. If I know what folders to look for and what files to expect, then I might be able to try things. 

Cheers
Charles

**Comment by ankitbinary** [comment]
did you try

npm install -g bower 
OR 
install -g bower

**Comment by chaaya61** [comment]
Install –g bower: gives me install is not a command
Npm install –g bower: gives me bower json is not found. This gives me hope, so where do I find bower json file? Do I download it from somewhere?

Cheers
Charles

**Comment by ankitbinary** [comment]
ok so do
npm install –g bower 

but do it in the webtrader folder you will see the bower file over there

**Comment by chaaya61** [comment]
npm install bower (without the -g) worked. I hope that's ok. I'll continue and see how it goes from here.

Cheers
Charles

Charles Chaaya

On 7 Apr 2016, at 3:35 PM, ankitbinary <notifications@github.com<mailto:notifications@github.com>> wrote:


ok so do
npm install -g bower

but do it in the webtrader folder you will see the bower file over there

-

**Comment by arnabk** [comment]
@chaaya61 That clearly indicates that you do not have admin permission in your machine or you did not start you console with admin permission

**Comment by chaaya61** [comment]
I am certainly the administrator, and I started the prompt as an Admin.

**Comment by chaaya61** [comment]
Apologies for my ignorance but what is "-g" for? It worked without it, isn't that good enough, or is it important to work with -g flag?

**Comment by chaaya61** [comment]
Now I issued grunt connect and I got a response saying Waiting forever
Started connect web server on http://0.0.0.0:9001

How do I test Webtrader now. I go localhost:9001 and I get Cannot get /
if I go localhost:9001/webtrader then I get Cannot get /webtrader

Thank you for your help.

**Comment by arnabk** [comment]
https://localhost:9001

**Comment by chaaya61** [comment]
Didn't work. With https I get the site couldn't be reached. Without the s, i.e http://localhost:9001, it I get  Cannot GET /

Obviously something is not installed properly.

**Comment by arnabk** [comment]
We are going too many times back and forth. Start teamviewer and we can have a quick look at it.

**Comment by chaaya61** [comment]
Thanks for that. Can we do this in 3 or 4 hours, as it is dinner time now and we will be having visitors after. I hope you don't mind and really appreciate your help.

**Comment by arnabk** [comment]
In the meantime, attach screenshots of everything. Like the npm install -g error message. then you page screenshot etc.

**Comment by chaaya61** [comment]
npm install -g bower:

![image](https://cloud.githubusercontent.com/assets/8502871/14344999/00b2b196-fcee-11e5-835a-f07047405ec1.png)

**Comment by chaaya61** [comment]
npm install -g grunt_cli

![image](https://cloud.githubusercontent.com/assets/8502871/14345041/3efcf858-fcee-11e5-8439-01ed0447f70b.png)

**Comment by chaaya61** [comment]
![image](https://cloud.githubusercontent.com/assets/8502871/14345071/65e0562c-fcee-11e5-9b1b-89a2f23c5dec.png)

**Comment by arnabk** [comment]
did you do 
cd webtrader
grunt
grunt connect

You have to follow the sequence. It mentioned in the documentation of the project

**Comment by chaaya61** [comment]
Thanks arnabk.
The command to run grunt first then grunt connect made all the difference. It is working now.

Note that the documentation doesn't say to grunt by itself. Here is what's included in the doc:
----------------------------------------------------------------------
####Windows Users
    * Download and install Git from [the official website](https://git-scm.com/download). Git Bash is included.
    * Download and install NodeJS from [the official website](https://www.nodejs.org). NPM is included.
    * Open Git Bash and run the following commands:
        $ git clone https://github.com/binary-com/webtrader.git
        $ cd webtrader
        $ install -g grunt-cli
        $ install -g bower
        $ npm install
        $ bower install
These will clone the repository, install `grunt-cli` and then resolve all of the dependencies from `package.json` and `bower.json` files.

At this point, your project is properly setup. You can now run following command to start a local server
        
        $ grunt connect:compressed
        For compressed file serving

        $ grunt connect:uncompressed
        For uncompressed file serving(this is default, you can just do grunt connect)

Running this command will launch local server at http://localhost:9001

------------------------------------------

So here is the sequence of steps that worked for me:

####Windows Users
    * Download and install Git from [the official website](https://git-scm.com/download). Git Bash is included.
    * Download and install NodeJS from [the official website](https://www.nodejs.org). NPM is included.
    * Open Git Bash and run the following commands:
        $ git clone https://github.com/binary-com/webtrader.git
        $ cd webtrader
        $ npm install grunt-cli
        $ npm install bower
        $ npm install
        $ bower install
        $ grunt
	$ grunt connect

Using Chrome go to http://localhost:9001

Thanks all who helped especially arnabk and ankitbinary.

**Comment by arnabk** [comment]
Documentation has been updated
